In [14]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [28]:
data=pd.read_csv("F:\TrainTest\AKI\Data\data1.csv")
data

SUBJECT_ID        BUN          CL  Creatinine       FiO2       GCS  \
0              34  33.000000  106.500000    1.500000  60.000000  4.571429   
1              36  20.333333  107.666667    0.966667  80.000000  3.888889   
2              85  17.000000  110.000000    1.400000  74.414218  5.000000   
3             107  34.333333   92.000000    3.033110  60.372946  5.000000   
4             109  48.000000  110.333333    2.816250  65.435791  4.944444   
...           ...        ...         ...         ...        ...       ...   
11729       99982  28.500000   98.000000    1.400000  64.614971  5.000000   
11730       99985  14.500000  104.500000    0.950000  75.833333  3.571429   
11731       99991  19.666667  113.333333    1.033333  26.666667  4.933333   
11732       99992  56.000000  104.000000    1.200000  60.175144  5.000000   
11733       99995  11.500000   99.500000    0.450000  50.000000  4.500000   

              GLU       HCO3        HCT          HR  ...         PO2  \
0      109.500000  27.000000  33.300000   54.666667  ...  127.033454   
1      110.666667  26.333333  34.550000   81.961538  ...   70.666667   
2      114.000000  17.000000  26.400000  102.956522  ...  103.894095   
3      107.500000  28.000000  38.500000   67.520000  ...   99.049690   
4      101.666667  16.000000  23.600000   89.218750  ...  128.295452   
...           ...        ...        ...         ...  ...         ...   
11729  100.500000  30.000000  27.977778   76.368421  ...  343.500000   
11730  106.500000  23.000000  28.700000   88.846154  ...   79.142857   
11731  139.000000  23.000000  27.950000  104.333333  ...  160.000000   
11732  110.000000  22.000000  28.933333   68.521739  ...  109.860369   
11733  120.500000  33.000000  27.400000   69.935484  ...  153.500000   

              PT        PTT      Pain       Resp       SpO2       Temp  \
0      28.600000  29.300000  0.000000  16.354839  96.160000  36.287037   
1      14.966667  43.375000  2.000000  16.736842  94.076923  37.166667   
2      10.010000  63.691200  0.000000  28.565217  98.304348  37.293651   
3      11.650000  21.500000  0.000000  19.200000  95.520000  36.522222   
4      22.900000  38.750000  6.375000  20.545455  99.343750  36.388889   
...          ...        ...       ...        ...        ...        ...   
11729  16.450000  36.650000  0.000000  16.421053  98.052632  36.666667   
11730  12.500000  47.700000  0.000000  17.543478  96.538462  37.759259   
11731  12.100000  27.800000  4.666667  26.266667  97.000000  37.090278   
11732  10.257500  44.261917  2.000000  15.695652  92.739130  36.416667   
11733  16.250000  31.300000  1.666667  18.714286  97.935484  37.000000   

       Tidal_Volume        WBC  Death  
0        586.500000   7.500000      0  
1        510.000000  13.100000      0  
2        367.852050   8.300000      0  
3        361.022046  11.650000      0  
4        493.029070   3.900000      1  
...             ...        ...    ...  
11729    485.626429   5.233333      0  
11730    474.500000  12.450000      0  
11731    469.603845   5.750000      0  
11732    523.037699  17.100000      0  
11733    317.750000   7.750000      0  

[11734 rows x 28 columns]

In [25]:
#实现归一化
scaler = MinMaxScaler() #实例化
scaler = scaler.fit(data) #fit，在这里本质是生成min(x)和max(x)
result = scaler.transform(data) #通过接口导出结果
result

array([[0.00000000e+00, 3.60000000e-01, 5.26422764e-01, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [8.06842020e-05, 2.15238095e-01, 5.59620596e-01, ...,
        1.90140845e-01, 1.00000000e+00, 0.00000000e+00],
       [1.61368404e-04, 1.77142857e-01, 6.26016260e-01, ...,
        1.97183099e-01, 1.00000000e+00, 1.00000000e+00],
       ...,
       [9.99757947e-01, 1.48571429e-01, 4.69512195e-01, ...,
        1.33802817e-01, 1.00000000e+00, 0.00000000e+00],
       [9.99919316e-01, 6.22857143e-01, 4.55284553e-01, ...,
        1.76056338e-01, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.14285714e-01, 3.27235772e-01, ...,
        2.57042254e-01, 0.00000000e+00, 1.00000000e+00]])

In [26]:
#不太熟悉numpy的小伙伴，能够判断data的结构吗？
#如果换成表是什么样子？
import pandas as pd
pd.DataFrame(result)

0         1         2         3         4         5         6   \
0      0.000000  0.360000  0.526423  0.208333  0.507888  0.811688  0.292357   
1      0.000081  0.215238  0.559621  0.134259  0.678606  0.656566  0.296815   
2      0.000161  0.177143  0.626016  0.194444  0.630926  0.909091  0.309554   
3      0.000242  0.375238  0.113821  0.421265  0.511071  0.909091  0.284713   
4      0.000323  0.531429  0.635501  0.391146  0.554287  0.896465  0.262420   
...         ...       ...       ...       ...       ...       ...       ...   
11178  0.999597  0.194286  0.810976  0.194444  0.740174  0.909091  0.221656   
11179  0.999677  0.308571  0.284553  0.194444  0.547281  0.909091  0.257962   
11180  0.999758  0.148571  0.469512  0.131944  0.643040  0.584416  0.280892   
11181  0.999919  0.622857  0.455285  0.166667  0.509383  0.909091  0.294268   
11182  1.000000  0.114286  0.327236  0.062500  0.422528  0.795455  0.334395   

             7         8         9   ...        20        21        22  \
0      0.620253  0.442095  0.169037  ...  0.158311  0.000000  0.182256   
1      0.594937  0.467271  0.461538  ...  0.343997  0.234043  0.188520   
2      0.240506  0.303122  0.686528  ...  0.612021  0.000000  0.382461   
3      0.658228  0.546828  0.306778  ...  0.055409  0.000000  0.228906   
4      0.202532  0.246727  0.539309  ...  0.282982  0.746011  0.250967   
...         ...       ...       ...  ...       ...       ...       ...   
11178  0.088608  0.355488  0.568221  ...  0.166227  0.000000  0.219478   
11179  0.734177  0.334900  0.401601  ...  0.255277  0.000000  0.183342   
11180  0.468354  0.349446  0.535316  ...  0.401055  0.000000  0.201746   
11181  0.430380  0.354146  0.317513  ...  0.355698  0.234043  0.171448   
11182  0.848101  0.323263  0.332663  ...  0.184697  0.195035  0.220942   

             23        24        25        26        27   28   29  
0      0.101197  0.461640  0.690058  0.193401  1.000000  1.0  1.0  
1      0.096117  0.587302  0.540936  0.339266  0.190141  1.0  0.0  
2      0.106427  0.605442  0.263844  0.214239  0.197183  1.0  1.0  
3      0.099636  0.495238  0.250530  0.301498  0.165493  1.0  0.0  
4      0.108962  0.476190  0.507854  0.099631  0.014085  0.0  1.0  
...         ...       ...       ...       ...       ...  ...  ...  
11178  0.106294  0.550265  0.549427  0.446060  0.172535  0.0  0.0  
11179  0.105813  0.515873  0.493424  0.134361  0.172535  1.0  1.0  
11180  0.102120  0.671958  0.471735  0.322336  0.133803  1.0  0.0  
11181  0.092854  0.480159  0.566350  0.443456  0.176056  0.0  0.0  
11182  0.105527  0.563492  0.166179  0.199913  0.257042  0.0  1.0  

[11183 rows x 30 columns]

当数据(x)按均值(μ)中心化后，再按标准差(σ)缩放，数据就会服从为均值为0，方差为1的正态分布（即标准正态分
布），而这个过程，就叫做数据标准化(Standardization，又称Z-score normalization)，

数据的标准化

In [29]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [31]:
data1=pd.read_csv("F:\TrainTest\AKI\Data\data1.csv")
data1

SUBJECT_ID        BUN          CL  Creatinine       FiO2       GCS  \
0              34  33.000000  106.500000    1.500000  60.000000  4.571429   
1              36  20.333333  107.666667    0.966667  80.000000  3.888889   
2              85  17.000000  110.000000    1.400000  74.414218  5.000000   
3             107  34.333333   92.000000    3.033110  60.372946  5.000000   
4             109  48.000000  110.333333    2.816250  65.435791  4.944444   
...           ...        ...         ...         ...        ...       ...   
11729       99982  28.500000   98.000000    1.400000  64.614971  5.000000   
11730       99985  14.500000  104.500000    0.950000  75.833333  3.571429   
11731       99991  19.666667  113.333333    1.033333  26.666667  4.933333   
11732       99992  56.000000  104.000000    1.200000  60.175144  5.000000   
11733       99995  11.500000   99.500000    0.450000  50.000000  4.500000   

              GLU       HCO3        HCT          HR  ...         PO2  \
0      109.500000  27.000000  33.300000   54.666667  ...  127.033454   
1      110.666667  26.333333  34.550000   81.961538  ...   70.666667   
2      114.000000  17.000000  26.400000  102.956522  ...  103.894095   
3      107.500000  28.000000  38.500000   67.520000  ...   99.049690   
4      101.666667  16.000000  23.600000   89.218750  ...  128.295452   
...           ...        ...        ...         ...  ...         ...   
11729  100.500000  30.000000  27.977778   76.368421  ...  343.500000   
11730  106.500000  23.000000  28.700000   88.846154  ...   79.142857   
11731  139.000000  23.000000  27.950000  104.333333  ...  160.000000   
11732  110.000000  22.000000  28.933333   68.521739  ...  109.860369   
11733  120.500000  33.000000  27.400000   69.935484  ...  153.500000   

              PT        PTT      Pain       Resp       SpO2       Temp  \
0      28.600000  29.300000  0.000000  16.354839  96.160000  36.287037   
1      14.966667  43.375000  2.000000  16.736842  94.076923  37.166667   
2      10.010000  63.691200  0.000000  28.565217  98.304348  37.293651   
3      11.650000  21.500000  0.000000  19.200000  95.520000  36.522222   
4      22.900000  38.750000  6.375000  20.545455  99.343750  36.388889   
...          ...        ...       ...        ...        ...        ...   
11729  16.450000  36.650000  0.000000  16.421053  98.052632  36.666667   
11730  12.500000  47.700000  0.000000  17.543478  96.538462  37.759259   
11731  12.100000  27.800000  4.666667  26.266667  97.000000  37.090278   
11732  10.257500  44.261917  2.000000  15.695652  92.739130  36.416667   
11733  16.250000  31.300000  1.666667  18.714286  97.935484  37.000000   

       Tidal_Volume        WBC  Death  
0        586.500000   7.500000      0  
1        510.000000  13.100000      0  
2        367.852050   8.300000      0  
3        361.022046  11.650000      0  
4        493.029070   3.900000      1  
...             ...        ...    ...  
11729    485.626429   5.233333      0  
11730    474.500000  12.450000      0  
11731    469.603845   5.750000      0  
11732    523.037699  17.100000      0  
11733    317.750000   7.750000      0  

[11734 rows x 28 columns]

In [33]:
#标准化
scaler=StandardScaler()
#实例化
scaler.fit(data1)
#查看均值属性
scaler.mean_

array([6.28303717e+04, 2.53586784e+01, 1.05511412e+02, 1.37702139e+00,
       5.86391475e+01, 3.94901376e+00, 1.34650912e+02, 2.38132124e+01,
       3.19048373e+01, 8.52270225e+01, 1.07647188e+01, 1.36760765e+00,
       4.21705471e+00, 1.38319930e+02, 4.76274300e+01, 5.97643029e+00,
       6.71653081e+00, 2.05605004e+02, 1.39460307e+02, 1.58497404e+01,
       3.63255521e+01, 1.97234997e+00, 1.82560052e+01, 9.68914103e+01,
       3.67492899e+01, 4.90533119e+02, 1.16549299e+01, 1.63030510e-01])

In [34]:
#查看方差属性
scaler.var_

array([5.67655646e+08, 2.77541685e+02, 2.97402981e+01, 1.22848195e+00,
       1.76204132e+02, 1.31337773e+00, 1.68118665e+03, 1.69224758e+01,
       2.93108923e+01, 2.36460856e+02, 3.31823914e+00, 3.03460804e-01,
       3.38799549e+00, 1.50845223e+01, 1.19915756e+02, 1.55245462e+00,
       5.82622284e-01, 8.18225205e+03, 3.70628959e+03, 1.35154268e+03,
       1.64313085e+02, 4.51188408e+00, 1.68523393e+01, 3.75282848e+01,
       3.22929030e-01, 5.77824512e+03, 2.92545685e+01, 1.36451563e-01])

In [36]:
#接口导出结果
x_Std=scaler.transform(data1)

In [37]:
#导出的结果是一个数组，用mean()查看均值
x_Std.mean()

2.902707820793075e-16

In [38]:
#用std()查看方差
x_Std.std()

1.0000000000000002

In [39]:
#使用fit_transform(data)一步达成结果
scaler.fit_transform(data1)

array([[-2.63567629,  0.45867426,  0.18127702, ...,  1.26247679,
        -0.76818682, -0.44134644],
       [-2.63559235, -0.30164892,  0.39520823, ...,  0.25609341,
         0.26717269, -0.44134644],
       [-2.63353573, -0.50173397,  0.82307062, ..., -1.61391095,
        -0.62027832, -0.44134644],
       ...,
       [ 1.55969819, -0.34166593,  1.43430262, ..., -0.27533167,
        -1.09173667, -0.44134644],
       [ 1.55974016,  1.83926109, -0.27714698, ...,  0.42760875,
         1.0067152 , -0.44134644],
       [ 1.55986608, -0.8318743 , -1.10231019, ..., -2.27302037,
        -0.72196541, -0.44134644]])